# Generated by Django 3.0.4 on 2020-06-17 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porfolio', '0002_auto_20200616_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='page',
            field=models.CharField(default='', editable=False, max_length=200, verbose_name='Pagina Web'),
        ),
    ]
