# Generated by Django 3.0.4 on 2020-06-17 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('porfolio', '0003_project_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='page',
            field=models.CharField(max_length=200, null=True, verbose_name='Pagina Web'),
        ),
    ]
